using System.Collections;
using System.Collections.Generic;
using UnityEngine;

[CreateAssetMenu(fileName = "New ResourceGen", menuName = "Create ResourceGen")]
public class ResourceGenerator : Builder {

	//The Type Resources Generated By This Building
	public string ResourceType;
	//How many resources will the player will receive from this building
	public int Resources;


}
